language: node_js
sudo: false
branches:
  only:
  - master
  - dev
git:
  depth: 1
node_js:
- '5'
before_script:
- chmod -R +x script
after_success:
- test $TRAVIS_BRANCH = "master" && script/deploy-gh-pages.sh
deploy:
  provider: npm
  email: me@platane.me
  on:
    branch: master
    repo: Platane/refinery-tools
  skip_cleanup: true
  api_key:
    secure: J3n/8KVePCiFEvhYOL8868pQX6mfypXZ+nvi991lx8zt//+ReysUTyfOyh6OiM/2E6bdCf5qzSJ4OaHlOZl9gsMVK/RDiA6/JrKC5nJHD+nxeLov44z4ki9/C6gaK1G9h6pb0w1k6GZSheS8w3eXNjLJhQLGiWWgnKtZmu6qkHDI61DKpJCECAsUtErUmysISFhIjet0TZWxuqWf/3PkI/2EHLCwU9MdP79XcOvwsWPW8jYoPvtrwIyoeHUHUP883wImWjQ9Af8Was6X7Z5lXQx+SzmTRJRGcItCkKTfZ9F13XMoWxKLA0we7tnEq2XKy0cPlVys6yfBtRADXRHVJWh/qF6NjfkSU+v1CsNY8Qb9mWHjhROgjo048osvvuKKYsov7Z3Fg7Mjhbwf/hvIgUFM4woNIuxSpyaTLsyw0Z9NUXMd+TqWe5EwwDODkI2a2w2Cb/yFraU+oP7fahWE2s6ZIq9R3eHw7ko9697wId4oPoGdeSD0VPurMV59RigiYDLeT0owX2twrUEDnnd0RZuFGOh0mhdaOGlwnnvo0OpNDv9x5bTHDyNDgv3SRti76Y1XcsM1sYJSBNFYp+Sw8ua88qYa0oLa7pc3VOG1DlnPOCVZB8eJjzEh36h8Dwh9W6WM98wK1o28dZvxD2UwM8AO1MmF00zlEmhw+lL8Epc=
