language: node_js

sudo: false

branches:
  only:
    - master

git:
  depth: 1

node_js:
  - "5"

install:
   # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # npm install for build
  - npm install

  - cd ./node_modules/october
  - npm run build
  - cd ../../

  # build, babel
  - webpack

script:
    # test
    - npm test

    # deploy to gh pages

    - cd ./dist
    - git init
    - git config user.name "Travis CI"
    - git config user.email "me@platane.me"
    - git add .
    - git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
