language: node_js

sudo: false

branches:
  only:
    - master
    - dev

git:
  depth: 1

node_js:
  - "5"

install:
    - npm install
    
    - cd ./node_modules/october
    - npm run build
    - cd ../../

before_script:
    - chmod -R +x script

after_success:

    # deploy demo
    - test $TRAVIS_BRANCH = "master" && script/deploy-gh-pages.sh
